# Generated by Django 4.1.7 on 2023-09-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tag_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='DateCreated',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
